services:
  - type: web
    name: assam-fps-service
    env: python
    plan: free
    buildCommand: |
      apt-get update && \
      apt-get install -y chromium-browser chromium-chromedriver && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
